// Generated by rstantools.  Do not edit by hand.

/*
    bayes4psy is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bayes4psy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bayes4psy.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by %%NAME%% %%VERSION%%
#include <stan/model/model_header.hpp>
namespace model_ttest_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'string', line 9, column 2 to column 10)",
                                                      " (in 'string', line 10, column 2 to column 22)",
                                                      " (in 'string', line 11, column 2 to column 32)",
                                                      " (in 'string', line 16, column 2 to column 13)",
                                                      " (in 'string', line 24, column 4 to column 48)",
                                                      " (in 'string', line 23, column 29 to line 25, column 3)",
                                                      " (in 'string', line 23, column 9 to line 25, column 3)",
                                                      " (in 'string', line 22, column 4 to column 49)",
                                                      " (in 'string', line 21, column 29 to line 23, column 3)",
                                                      " (in 'string', line 21, column 9 to line 25, column 3)",
                                                      " (in 'string', line 20, column 4 to column 50)",
                                                      " (in 'string', line 19, column 29 to line 21, column 3)",
                                                      " (in 'string', line 19, column 9 to line 25, column 3)",
                                                      " (in 'string', line 18, column 4 to column 51)",
                                                      " (in 'string', line 17, column 22 to line 19, column 3)",
                                                      " (in 'string', line 17, column 2 to line 25, column 3)",
                                                      " (in 'string', line 27, column 2 to column 9)",
                                                      " (in 'string', line 35, column 4 to column 51)",
                                                      " (in 'string', line 34, column 29 to line 36, column 3)",
                                                      " (in 'string', line 34, column 9 to line 36, column 3)",
                                                      " (in 'string', line 33, column 4 to column 52)",
                                                      " (in 'string', line 32, column 29 to line 34, column 3)",
                                                      " (in 'string', line 32, column 9 to line 36, column 3)",
                                                      " (in 'string', line 31, column 4 to column 53)",
                                                      " (in 'string', line 30, column 29 to line 32, column 3)",
                                                      " (in 'string', line 30, column 9 to line 36, column 3)",
                                                      " (in 'string', line 29, column 4 to column 54)",
                                                      " (in 'string', line 28, column 22 to line 30, column 3)",
                                                      " (in 'string', line 28, column 2 to line 36, column 3)",
                                                      " (in 'string', line 38, column 2 to column 9)",
                                                      " (in 'string', line 48, column 4 to column 31)",
                                                      " (in 'string', line 47, column 9 to line 49, column 3)",
                                                      " (in 'string', line 46, column 4 to column 48)",
                                                      " (in 'string', line 45, column 29 to line 47, column 3)",
                                                      " (in 'string', line 45, column 9 to line 49, column 3)",
                                                      " (in 'string', line 44, column 4 to column 49)",
                                                      " (in 'string', line 43, column 29 to line 45, column 3)",
                                                      " (in 'string', line 43, column 9 to line 49, column 3)",
                                                      " (in 'string', line 42, column 4 to column 50)",
                                                      " (in 'string', line 41, column 29 to line 43, column 3)",
                                                      " (in 'string', line 41, column 9 to line 49, column 3)",
                                                      " (in 'string', line 40, column 4 to column 51)",
                                                      " (in 'string', line 39, column 22 to line 41, column 3)",
                                                      " (in 'string', line 39, column 2 to line 49, column 3)",
                                                      " (in 'string', line 50, column 2 to column 31)",
                                                      " (in 'string', line 2, column 2 to column 17)",
                                                      " (in 'string', line 3, column 9 to column 10)",
                                                      " (in 'string', line 3, column 2 to column 12)",
                                                      " (in 'string', line 5, column 2 to column 24)",
                                                      " (in 'string', line 6, column 2 to column 19)"};
#include <stan_meta_header.hpp>
class model_ttest final : public model_base_crtp<model_ttest> {
private:
  int n;
  std::vector<double> y;
  std::vector<int> p_ids;
  std::vector<double> p_values;
 
public:
  ~model_ttest() { }
  
  inline std::string model_name() const final { return "model_ttest"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = %%NAME%%3 %%VERSION%%", "stancflags = "};
  }
  
  
  model_ttest(stan::io::var_context& context__,
              unsigned int random_seed__ = 0,
              std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_ttest_namespace::model_ttest";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 46;
      context__.validate_dims("data initialization","n","int",
          context__.to_vec());
      n = std::numeric_limits<int>::min();
      
      current_statement__ = 46;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 46;
      current_statement__ = 46;
      check_greater_or_equal(function__, "n", n, 0);
      current_statement__ = 47;
      validate_non_negative_index("y", "n", n);
      current_statement__ = 48;
      context__.validate_dims("data initialization","y","double",
          context__.to_vec(n));
      y = std::vector<double>(n, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 48;
      assign(y, nil_index_list(), context__.vals_r("y"),
        "assigning variable y");
      current_statement__ = 49;
      context__.validate_dims("data initialization","p_ids","int",
          context__.to_vec(3));
      p_ids = std::vector<int>(3, std::numeric_limits<int>::min());
      
      current_statement__ = 49;
      assign(p_ids, nil_index_list(), context__.vals_i("p_ids"),
        "assigning variable p_ids");
      current_statement__ = 49;
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        current_statement__ = 49;
        current_statement__ = 49;
        check_greater_or_equal(function__, "p_ids[sym1__]",
                               p_ids[(sym1__ - 1)], 0);}
      current_statement__ = 50;
      context__.validate_dims("data initialization","p_values","double",
          context__.to_vec(6));
      p_values = std::vector<double>(6, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 50;
      assign(p_values, nil_index_list(), context__.vals_r("p_values"),
        "assigning variable p_values");
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_ttest_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      local_scalar_t__ mu;
      mu = DUMMY_VAR__;
      
      current_statement__ = 1;
      mu = in__.scalar();
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      current_statement__ = 2;
      sigma = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        sigma = stan::math::lb_constrain(sigma, 0, lp__);
      } else {
        current_statement__ = 2;
        sigma = stan::math::lb_constrain(sigma, 0);
      }
      local_scalar_t__ nu;
      nu = DUMMY_VAR__;
      
      current_statement__ = 3;
      nu = in__.scalar();
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        nu = stan::math::lub_constrain(nu, 0, 10000, lp__);
      } else {
        current_statement__ = 3;
        nu = stan::math::lub_constrain(nu, 0, 10000);
      }
      {
        int id;
        id = std::numeric_limits<int>::min();
        
        current_statement__ = 4;
        id = 1;
        current_statement__ = 16;
        if (logical_eq(p_ids[(id - 1)], 1)) {
          current_statement__ = 14;
          lp_accum__.add(
            uniform_lpdf<propto__>(mu, p_values[(((id * 2) - 1) - 1)],
              p_values[((id * 2) - 1)]));
        } else {
          current_statement__ = 13;
          if (logical_eq(p_ids[(id - 1)], 2)) {
            current_statement__ = 11;
            lp_accum__.add(
              normal_lpdf<propto__>(mu, p_values[(((id * 2) - 1) - 1)],
                p_values[((id * 2) - 1)]));
          } else {
            current_statement__ = 10;
            if (logical_eq(p_ids[(id - 1)], 3)) {
              current_statement__ = 8;
              lp_accum__.add(
                gamma_lpdf<propto__>(mu, p_values[(((id * 2) - 1) - 1)],
                  p_values[((id * 2) - 1)]));
            } else {
              current_statement__ = 7;
              if (logical_eq(p_ids[(id - 1)], 4)) {
                current_statement__ = 5;
                lp_accum__.add(
                  beta_lpdf<propto__>(mu, p_values[(((id * 2) - 1) - 1)],
                    p_values[((id * 2) - 1)]));
              } 
            }
          }
        }
        current_statement__ = 17;
        id = 2;
        current_statement__ = 29;
        if (logical_eq(p_ids[(id - 1)], 1)) {
          current_statement__ = 27;
          lp_accum__.add(
            uniform_lpdf<propto__>(sigma, p_values[(((id * 2) - 1) - 1)],
              p_values[((id * 2) - 1)]));
        } else {
          current_statement__ = 26;
          if (logical_eq(p_ids[(id - 1)], 2)) {
            current_statement__ = 24;
            lp_accum__.add(
              normal_lpdf<propto__>(sigma, p_values[(((id * 2) - 1) - 1)],
                p_values[((id * 2) - 1)]));
          } else {
            current_statement__ = 23;
            if (logical_eq(p_ids[(id - 1)], 3)) {
              current_statement__ = 21;
              lp_accum__.add(
                gamma_lpdf<propto__>(sigma, p_values[(((id * 2) - 1) - 1)],
                  p_values[((id * 2) - 1)]));
            } else {
              current_statement__ = 20;
              if (logical_eq(p_ids[(id - 1)], 4)) {
                current_statement__ = 18;
                lp_accum__.add(
                  beta_lpdf<propto__>(sigma, p_values[(((id * 2) - 1) - 1)],
                    p_values[((id * 2) - 1)]));
              } 
            }
          }
        }
        current_statement__ = 30;
        id = 3;
        current_statement__ = 44;
        if (logical_eq(p_ids[(id - 1)], 1)) {
          current_statement__ = 42;
          lp_accum__.add(
            uniform_lpdf<propto__>(nu, p_values[(((id * 2) - 1) - 1)],
              p_values[((id * 2) - 1)]));
        } else {
          current_statement__ = 41;
          if (logical_eq(p_ids[(id - 1)], 2)) {
            current_statement__ = 39;
            lp_accum__.add(
              normal_lpdf<propto__>(nu, p_values[(((id * 2) - 1) - 1)],
                p_values[((id * 2) - 1)]));
          } else {
            current_statement__ = 38;
            if (logical_eq(p_ids[(id - 1)], 3)) {
              current_statement__ = 36;
              lp_accum__.add(
                gamma_lpdf<propto__>(nu, p_values[(((id * 2) - 1) - 1)],
                  p_values[((id * 2) - 1)]));
            } else {
              current_statement__ = 35;
              if (logical_eq(p_ids[(id - 1)], 4)) {
                current_statement__ = 33;
                lp_accum__.add(
                  beta_lpdf<propto__>(nu, p_values[(((id * 2) - 1) - 1)],
                    p_values[((id * 2) - 1)]));
              } else {
                current_statement__ = 31;
                lp_accum__.add(exponential_lpdf<propto__>(nu, (1.0 / 29.0)));
              }
            }
          }
        }
        current_statement__ = 45;
        lp_accum__.add(student_t_lpdf<propto__>(y, nu, mu, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_ttest_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      double mu;
      mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      mu = in__.scalar();
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma = in__.scalar();
      current_statement__ = 2;
      sigma = stan::math::lb_constrain(sigma, 0);
      double nu;
      nu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      nu = in__.scalar();
      current_statement__ = 3;
      nu = stan::math::lub_constrain(nu, 0, 10000);
      vars__.emplace_back(mu);
      vars__.emplace_back(sigma);
      vars__.emplace_back(nu);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double mu;
      mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      mu = context__.vals_r("mu")[(1 - 1)];
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      double sigma_free__;
      sigma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma_free__ = stan::math::lb_free(sigma, 0);
      double nu;
      nu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      nu = context__.vals_r("nu")[(1 - 1)];
      double nu_free__;
      nu_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      nu_free__ = stan::math::lub_free(nu, 0, 10000);
      vars__.emplace_back(mu);
      vars__.emplace_back(sigma_free__);
      vars__.emplace_back(nu_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("mu");
    names__.emplace_back("sigma");
    names__.emplace_back("nu");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "nu");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "nu");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_ttest_namespace::model_ttest;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_ttest_namespace::profiles__;
}
#endif
#endif
